version: 2
jobs:
  build:
    docker:
      - image: noxaro/cmake-jdk

    working_directory: /build

    steps:
      - checkout
      - run: cmake .
      - run: make
      - run: build-wrapper-linux-x86-64 --out-dir bw-output make clean all
      - run: sonar-scanner -Dsonar.projectKey=server-plugin -Dsonar.sources=. -Dsonar.cfamily.build-wrapper-output=bw-output -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ragemp-java -Dsonar.login=${sonarqube_api_key}

      - store_artifacts:
          path: /build/build/libRageJava.so
